name: Jekyll Site Build

on:
  push:
    branches:
      - main  # Replace 'main' with the name of your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # You can change this version if needed

    - name: Install Dependencies
      run: |
        bundle install

    - name: Build Site
      run: |
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site



