name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvips42 libvips-dev libmagickwand-dev imagemagick
    
    - name: Configure Bundler
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle config set --local frozen 'false'
        bundle config set --local without 'development test'
    
    - name: Install Ruby dependencies
      run: |
        bundle install --jobs 4 --retry 3
        
    - name: Build site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2